services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"   # RTSP 
      - "8888:8888"   # HLS
      - "8889:8889"   # WebRTC
    restart: unless-stopped
    networks: [traffic-net]

  cam_north:
    image: linuxserver/ffmpeg:latest
    container_name: cam_north
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/main_video.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/north
    restart: unless-stopped
    networks: [traffic-net]

  cam_east:
    image: linuxserver/ffmpeg:latest
    container_name: cam_east
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/main_video.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/east
    restart: unless-stopped
    networks: [traffic-net]

  cam_south:
    image: linuxserver/ffmpeg:latest
    container_name: cam_south
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/main_video.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/south
    restart: unless-stopped
    networks: [traffic-net]

  cam_west:
    image: linuxserver/ffmpeg:latest
    container_name: cam_west
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/main_video.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/west
    restart: unless-stopped
    networks: [traffic-net]

  cam_north_1:
    image: linuxserver/ffmpeg:latest
    container_name: cam_north_1
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/new.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/north1
    restart: unless-stopped
    networks: [traffic-net]

  cam_east_1:
    image: linuxserver/ffmpeg:latest
    container_name: cam_east_1
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/new.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/east1
    restart: unless-stopped
    networks: [traffic-net]

  cam_south_1:
    image: linuxserver/ffmpeg:latest
    container_name: cam_south_1
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/new.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/south1
    restart: unless-stopped
    networks: [traffic-net]

  cam_west_1:
    image: linuxserver/ffmpeg:latest
    container_name: cam_west_1
    depends_on: [mediamtx]
    volumes:
      - ./videos:/videos:ro
    command: >
      -re -stream_loop -1 -fflags +genpts -i /videos/new.mp4
      -an
      -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/west1
    restart: unless-stopped
    networks: [traffic-net]

networks:
  traffic-net:
    external: true  
