backend_url: "http://localhost:3000"
namespace: "/ingest"
model_path: "models/best.onnx"

cameras:
  - id: 1
    name: "Road 1 (Bac)"
    rtsp: "rtsp://localhost:8554/north"
    max_vehicles: 5
    default_green: 42
    emergency_green: 80
    roi:
      - [205, 123]  
      - [251, 124]  
      - [213, 287] 
      - [1, 224]
    count_line:
      p1: [148, 159]
      p2: [237, 158]
    line_dir: null
  - id: 2
    name: "Road 2 (Dong)"
    rtsp: "rtsp://localhost:8554/east"
    max_vehicles: 5
    default_green: 42
    emergency_green: 80
    roi:
      - [205, 123]  
      - [251, 124]  
      - [213, 287] 
      - [1, 224]
    count_line:
      p1: [148, 159]
      p2: [237, 158]
    line_dir: null
  - id: 3
    name: "Road 3 (Nam)"
    rtsp: "rtsp://localhost:8554/south"
    max_vehicles: 5
    default_green: 42
    emergency_green: 80
    roi:
      - [205, 123]  
      - [251, 124]  
      - [213, 287] 
      - [1, 224]
    count_line:
      p1: [148, 159]
      p2: [237, 158]
    line_dir: null
  - id: 4
    name: "Road 4 (Tay)"
    rtsp: "rtsp://localhost:8554/west"
    max_vehicles: 5
    default_green: 42
    emergency_green: 80
    roi:
      - [205, 123]  
      - [251, 124]  
      - [213, 287] 
      - [1, 224]
    count_line:
      p1: [148, 159]
      p2: [237, 158]
    line_dir: null
